#!/usr/bin/env python3
"""
Regenerate FOLLOWUPS.md from .taskstate/*.json sidecars + _notes.json.

FOLLOWUPS.md is a derived artifact — the source-of-truth for each task's
follow-ups is its sidecar's `follow_ups: []` array. This script rebuilds the
register table from those arrays and must be run inside /ship and /triage so
the register never drifts from sidecars.

Ordering (deterministic):
  1. Task rows grouped by phase prefix in the order they appear in
     `prefixes:` of `ritual.config.yaml` (falls back to alphabetical when
     the config is unreadable). Within a phase, numeric ID ascending;
     within a task, array order preserved from the sidecar.
  2. Non-task notes from .taskstate/_notes.json appended after a sub-header.

Pipe characters in free text are escaped as `\\|` so markdown table parsing
is preserved.

Usage:
    python3 scripts/regen-followups.py [OUT=FOLLOWUPS.md] [STATE_DIR=.taskstate]
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

def _load_phase_order() -> list[str]:
    """Read prefixes order from ritual.config.yaml. Empty/missing → []."""
    cfg = Path("ritual.config.yaml")
    if not cfg.exists():
        return []
    try:
        import yaml  # type: ignore[import-not-found]
        data = yaml.safe_load(cfg.read_text()) or {}
        prefixes = data.get("prefixes") or {}
        return list(prefixes.keys()) if isinstance(prefixes, dict) else []
    except Exception:
        return []


PHASE_ORDER = _load_phase_order()
TASK_ID = re.compile(r"^([A-Z]+)-(\d+)([a-z]?)$")

HEADER = """# Follow-ups register

<!--
Generated by scripts/regen-followups.py from .taskstate/*.json sidecars.
DO NOT EDIT BY HAND — edits here are overwritten on every /ship and /triage.
To change a disposition, edit the `follow_ups` array in the originating
sidecar (.taskstate/<SOURCE>.json) and re-run scripts/regen-followups.py.
-->

> Append-only register. Every `Follow-ups:` bullet in [BUILDLOG.md](BUILDLOG.md) gets exactly one row here, recording its disposition. Produced by `/ship` (Step 7.5 — triage) and `/triage <ID>`. See [ADR 0006](decisions/0006-followup-triage-register.md) and [ADR 0021](decisions/0021-reduce-context-bloat-buildlog-followups.md).

## Columns

| Field         | Meaning                                                                                                                                                                 |
| ------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Source        | The shipped task ID that produced the bullet (its BUILDLOG entry).                                                                                                      |
| Follow-up     | Short description — copied or paraphrased from the BUILDLOG bullet.                                                                                                     |
| Disposition   | `promoted` / `folded` / `dropped` / `resolved`.                                                                                                                         |
| Target / Note | For `promoted`: the new task ID. For `folded`: the task ID it was absorbed into. For `dropped`: short reason. For `resolved`: the resolver task ID + optional line ref. |
| Decided       | ISO date the triage call was made.                                                                                                                                      |

## Dispositions

- **promoted** — spawned a new MASTERPLAN row + `.taskstate/<NEW-ID>.json`. Target column is the new ID.
- **folded** — absorbed into the acceptance criteria of an existing (planned or shipped) task. Target column is that task ID.
- **dropped** — nit too small for a PR; will be fixed opportunistically when nearby code is next touched. Note column explains.
- **resolved** — already addressed by a task that shipped later. Target column points at that resolver.

## Rules

1. Append-only. Never edit a row retroactively. If a disposition was wrong, add a new row referencing the earlier row in the Note column.
2. One bullet → one row. Bundling multiple bullets into one promoted task is allowed — each bullet still gets its own row, all pointing at the same Target ID.
3. Every bullet in BUILDLOG must appear here. `/plan-next`'s drift gate enforces this.
4. ID allocation for `promoted`: suggested by the triage step, confirmed by the shipper. Before any MASTERPLAN append, the step greps for the proposed ID and fails loud on collision.

---

## Register

"""

NOTES_HEADER = """
## Non-task notes

> Sources that do not map to a BUILDLOG task (strategy/data notes captured inline during triage). Kept here for audit continuity.

"""


def escape_cell(value: str) -> str:
    return value.replace("|", "\\|")


def format_target_note(entry: dict) -> str:
    target = entry.get("target")
    note = entry.get("note")
    if target and note:
        return f"{target} ({note})"
    if target:
        return target
    return note or ""


def phase_key(task_id: str) -> tuple[int, int, str]:
    m = TASK_ID.match(task_id)
    if not m:
        return (len(PHASE_ORDER), 0, task_id)
    phase, num, suffix = m.group(1), int(m.group(2)), m.group(3)
    phase_idx = PHASE_ORDER.index(phase) if phase in PHASE_ORDER else len(PHASE_ORDER)
    return (phase_idx, num, suffix)


def build_row(source: str, entry: dict) -> str:
    text = escape_cell(entry.get("text", ""))
    disposition = entry.get("disposition", "")
    target_note = escape_cell(format_target_note(entry))
    decided = entry.get("decided", "")
    return f"| {source} | {text} | {disposition} | {target_note} | {decided} |\n"


def collect(state_dir: Path) -> tuple[list[tuple[str, dict]], list[dict]]:
    task_rows: list[tuple[str, dict]] = []
    for sidecar in sorted(state_dir.glob("*.json")):
        if sidecar.name.startswith("_"):
            continue
        try:
            data = json.loads(sidecar.read_text())
        except json.JSONDecodeError as exc:
            print(f"warn: {sidecar}: {exc}", file=sys.stderr)
            continue
        source_id = data.get("id")
        if not source_id:
            continue
        for entry in data.get("follow_ups", []) or []:
            task_rows.append((source_id, entry))

    notes_path = state_dir / "_notes.json"
    notes: list[dict] = []
    if notes_path.is_file():
        notes = json.loads(notes_path.read_text()).get("notes", []) or []

    task_rows.sort(key=lambda t: phase_key(t[0]))
    return task_rows, notes


def render(task_rows: list[tuple[str, dict]], notes: list[dict]) -> str:
    parts = [HEADER]
    parts.append("| Source | Follow-up | Disposition | Target / Note | Decided |\n")
    parts.append("| ------ | --------- | ----------- | ------------- | ------- |\n")
    for source, entry in task_rows:
        parts.append(build_row(source, entry))
    if notes:
        parts.append(NOTES_HEADER)
        parts.append("| Source | Follow-up | Disposition | Target / Note | Decided |\n")
        parts.append("| ------ | --------- | ----------- | ------------- | ------- |\n")
        for note in notes:
            parts.append(build_row(note["source"], note))
    return "".join(parts)


def main(argv: list[str]) -> int:
    out_path = Path(argv[1]) if len(argv) > 1 else Path("FOLLOWUPS.md")
    state_dir = Path(argv[2]) if len(argv) > 2 else Path(".taskstate")
    if not state_dir.is_dir():
        print(f"error: {state_dir} not found", file=sys.stderr)
        return 1
    task_rows, notes = collect(state_dir)
    out_path.write_text(render(task_rows, notes))
    print(
        f"wrote {out_path}: {len(task_rows)} task row(s) + {len(notes)} note(s)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
